name: CI: Android build (JDK 17 + SDK + licenses) and upload APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK + accept licenses
        uses: android-actions/setup-android@v3
      - run: yes | sdkmanager --licenses

      - name: Build debug APK
        run: ./gradlew --no-daemon clean assembleDebug
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: traccar-client-debug
          path: app/build/outputs/apk/debug/*.apk
